In [43]:
import numpy as np

In [44]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [45]:
X = np.array([  [0,1,1],
                [1,1,1],
                [1,0,0],])

In [46]:
X

array([[0, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [47]:
y = np.array([[0,1,1]]).T

In [48]:
y

array([[0],
       [1],
       [1]])

In [49]:
np.random.seed(1)

In [50]:
syn0 = 2*np.random.random((3,1)) - 1

In [51]:
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [52]:
for iter in range(10000):

    # forward prop
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # error
    l1_error = y - l1

    # back prop
    l1_delta = l1_error * nonlin(l1,True)

    # weights update
    syn0 += np.dot(l0.T,l1_delta)

In [53]:
l0

array([[0, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [54]:
l1

array([[0.01142146],
       [0.98979175],
       [0.99988086]])

In [55]:
l1_error

array([[-0.01142146],
       [ 0.01020825],
       [ 0.00011914]])

In [56]:
l1_delta

array([[-1.28959798e-04],
       [ 1.03144553e-04],
       [ 1.41932018e-08]])

In [57]:
syn0

array([[ 9.0351758 ],
       [-1.51020277],
       [-2.95062301]])

In [58]:
print ("Trained output:")
print (l1)

Trained output:
[[0.01142146]
 [0.98979175]
 [0.99988086]]
